### ISSUE TITLE
Portrait-Landscape resetting

### ISSUE THREAD

**Issue by John-J-Russell** [aqknutsen/EECS448ClockProject#1]
Upon switching from portrait to landscape (or vice versa) clock resets to 00:00:00.

Update 11 Feb, 8:30 a.m.: Changing orientation now resets time to 12:00:00 A.M., even if in military time.
Miltime:
Note that upon changing the time after re-orientating, the hour will default to 12, even if the spinners initialize at zero.

Update 12 Feb, 7:30 a.m.: Time change on orientation fixed, but the clock now sinks into the spinners in landscape.

**Comment by cesar-avalos3** [comment]
Initializing the NumberPickers inside onStart() rather than onCreate() should fix the issue
